id: I3837A52A
legacy_id: P010648
ocr_import_info:
  bdrc_scan_id: W1KG21020
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T19:19:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T10:31:54.866671+00:00'
last_modified: 2022-08-31 18:32:41.654447
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG21020
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG21020
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མན་ངག་རྒྱུད་ཀྱི་འགྲེལ་པ།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.47032994398164313
  ocr_word_median_confidence_index: 0.4099999964237213
quality: null
bases:
  I1KG21100:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG21100
      total_pages: 1078
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG21100.txt
    statistics:
      ocr_word_median_confidence_index: 0.4099999964237213
      ocr_word_mean_confidence_index: 0.47032994398164313
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
