id: P010648
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21020
  title: མན་ངག་རྒྱུད་ཀྱི་འགྲེལ་པ།
  author: ''
  volumes:
    617eacf10cc74d249eba2947a8b5c762:
      image_group_id: I1KG21100
      title: ''
      volume_number: 1
      total_pages: 1078
      base_file: v001.txt
